// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/gate_game.proto

#ifndef PROTOBUF_INCLUDED_proto_2fgate_5fgame_2eproto
#define PROTOBUF_INCLUDED_proto_2fgate_5fgame_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/service.h>
#include "proto/common.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_proto_2fgate_5fgame_2eproto 

namespace protobuf_proto_2fgate_5fgame_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_proto_2fgate_5fgame_2eproto
namespace proto {
}  // namespace proto
namespace proto {

// ===================================================================


// ===================================================================

class IGameService_Stub;

class IGameService : public ::google::protobuf::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline IGameService() {};
 public:
  virtual ~IGameService();

  typedef IGameService_Stub Stub;

  static const ::google::protobuf::ServiceDescriptor* descriptor();

  virtual void loginRequest(::google::protobuf::RpcController* controller,
                       const ::proto::LoginRequest* request,
                       ::proto::None* response,
                       ::google::protobuf::Closure* done);
  virtual void callEntityRpc(::google::protobuf::RpcController* controller,
                       const ::proto::RpcMessage* request,
                       ::proto::None* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::google::protobuf::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::google::protobuf::MethodDescriptor* method,
                  ::google::protobuf::RpcController* controller,
                  const ::google::protobuf::Message* request,
                  ::google::protobuf::Message* response,
                  ::google::protobuf::Closure* done);
  const ::google::protobuf::Message& GetRequestPrototype(
    const ::google::protobuf::MethodDescriptor* method) const;
  const ::google::protobuf::Message& GetResponsePrototype(
    const ::google::protobuf::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(IGameService);
};

class IGameService_Stub : public IGameService {
 public:
  IGameService_Stub(::google::protobuf::RpcChannel* channel);
  IGameService_Stub(::google::protobuf::RpcChannel* channel,
                   ::google::protobuf::Service::ChannelOwnership ownership);
  ~IGameService_Stub();

  inline ::google::protobuf::RpcChannel* channel() { return channel_; }

  // implements IGameService ------------------------------------------

  void loginRequest(::google::protobuf::RpcController* controller,
                       const ::proto::LoginRequest* request,
                       ::proto::None* response,
                       ::google::protobuf::Closure* done);
  void callEntityRpc(::google::protobuf::RpcController* controller,
                       const ::proto::RpcMessage* request,
                       ::proto::None* response,
                       ::google::protobuf::Closure* done);
 private:
  ::google::protobuf::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(IGameService_Stub);
};


// -------------------------------------------------------------------

class IGameClientService_Stub;

class IGameClientService : public ::google::protobuf::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline IGameClientService() {};
 public:
  virtual ~IGameClientService();

  typedef IGameClientService_Stub Stub;

  static const ::google::protobuf::ServiceDescriptor* descriptor();

  virtual void loginReply(::google::protobuf::RpcController* controller,
                       const ::proto::LoginReply* request,
                       ::proto::None* response,
                       ::google::protobuf::Closure* done);
  virtual void callEntityRpc(::google::protobuf::RpcController* controller,
                       const ::proto::RpcMessage* request,
                       ::proto::None* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::google::protobuf::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::google::protobuf::MethodDescriptor* method,
                  ::google::protobuf::RpcController* controller,
                  const ::google::protobuf::Message* request,
                  ::google::protobuf::Message* response,
                  ::google::protobuf::Closure* done);
  const ::google::protobuf::Message& GetRequestPrototype(
    const ::google::protobuf::MethodDescriptor* method) const;
  const ::google::protobuf::Message& GetResponsePrototype(
    const ::google::protobuf::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(IGameClientService);
};

class IGameClientService_Stub : public IGameClientService {
 public:
  IGameClientService_Stub(::google::protobuf::RpcChannel* channel);
  IGameClientService_Stub(::google::protobuf::RpcChannel* channel,
                   ::google::protobuf::Service::ChannelOwnership ownership);
  ~IGameClientService_Stub();

  inline ::google::protobuf::RpcChannel* channel() { return channel_; }

  // implements IGameClientService ------------------------------------------

  void loginReply(::google::protobuf::RpcController* controller,
                       const ::proto::LoginReply* request,
                       ::proto::None* response,
                       ::google::protobuf::Closure* done);
  void callEntityRpc(::google::protobuf::RpcController* controller,
                       const ::proto::RpcMessage* request,
                       ::proto::None* response,
                       ::google::protobuf::Closure* done);
 private:
  ::google::protobuf::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(IGameClientService_Stub);
};


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace proto

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_proto_2fgate_5fgame_2eproto
