# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/client_gate.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import common_pb2 as proto_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/client_gate.proto',
  package='proto',
  syntax='proto3',
  serialized_options=_b('\200\001\001\220\001\001'),
  serialized_pb=_b('\n\x17proto/client_gate.proto\x12\x05proto\x1a\x12proto/common.proto\"\x1b\n\x0bSessionSeed\x12\x0c\n\x04seed\x18\x01 \x01(\x04\"(\n\rEncryptKeyStr\x12\x17\n\x0f\x65ncrypt_key_str\x18\x01 \x01(\x0c\"[\n\nEncryptKey\x12\x15\n\rrandom_header\x18\x01 \x01(\x0c\x12\x13\n\x0b\x65ncrypt_key\x18\x02 \x01(\x0c\x12\x0c\n\x04seed\x18\x03 \x01(\x04\x12\x13\n\x0brandom_tail\x18\x04 \x01(\x0c\x32\xd8\x01\n\x0cIGateService\x12-\n\x11sesionSeedRequest\x12\x0b.proto.None\x1a\x0b.proto.None\x12\x36\n\x11\x65ncryptKeyRequest\x12\x14.proto.EncryptKeyStr\x1a\x0b.proto.None\x12\x30\n\x0cloginRequest\x12\x13.proto.LoginRequest\x1a\x0b.proto.None\x12/\n\rcallEntityRpc\x12\x11.proto.RpcMessage\x1a\x0b.proto.None2\xca\x01\n\x0eIClientService\x12,\n\x10sessionSeedReply\x12\x0b.proto.None\x1a\x0b.proto.None\x12+\n\x0f\x65ncryptKeyReply\x12\x0b.proto.None\x1a\x0b.proto.None\x12,\n\nloginReply\x12\x11.proto.LoginReply\x1a\x0b.proto.None\x12/\n\rcallEntityRpc\x12\x11.proto.RpcMessage\x1a\x0b.proto.NoneB\x06\x80\x01\x01\x90\x01\x01\x62\x06proto3')
  ,
  dependencies=[proto_dot_common__pb2.DESCRIPTOR,])




_SESSIONSEED = _descriptor.Descriptor(
  name='SessionSeed',
  full_name='proto.SessionSeed',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seed', full_name='proto.SessionSeed.seed', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=81,
)


_ENCRYPTKEYSTR = _descriptor.Descriptor(
  name='EncryptKeyStr',
  full_name='proto.EncryptKeyStr',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='encrypt_key_str', full_name='proto.EncryptKeyStr.encrypt_key_str', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=123,
)


_ENCRYPTKEY = _descriptor.Descriptor(
  name='EncryptKey',
  full_name='proto.EncryptKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='random_header', full_name='proto.EncryptKey.random_header', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='encrypt_key', full_name='proto.EncryptKey.encrypt_key', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seed', full_name='proto.EncryptKey.seed', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='random_tail', full_name='proto.EncryptKey.random_tail', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=216,
)

DESCRIPTOR.message_types_by_name['SessionSeed'] = _SESSIONSEED
DESCRIPTOR.message_types_by_name['EncryptKeyStr'] = _ENCRYPTKEYSTR
DESCRIPTOR.message_types_by_name['EncryptKey'] = _ENCRYPTKEY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SessionSeed = _reflection.GeneratedProtocolMessageType('SessionSeed', (_message.Message,), dict(
  DESCRIPTOR = _SESSIONSEED,
  __module__ = 'proto.client_gate_pb2'
  # @@protoc_insertion_point(class_scope:proto.SessionSeed)
  ))
_sym_db.RegisterMessage(SessionSeed)

EncryptKeyStr = _reflection.GeneratedProtocolMessageType('EncryptKeyStr', (_message.Message,), dict(
  DESCRIPTOR = _ENCRYPTKEYSTR,
  __module__ = 'proto.client_gate_pb2'
  # @@protoc_insertion_point(class_scope:proto.EncryptKeyStr)
  ))
_sym_db.RegisterMessage(EncryptKeyStr)

EncryptKey = _reflection.GeneratedProtocolMessageType('EncryptKey', (_message.Message,), dict(
  DESCRIPTOR = _ENCRYPTKEY,
  __module__ = 'proto.client_gate_pb2'
  # @@protoc_insertion_point(class_scope:proto.EncryptKey)
  ))
_sym_db.RegisterMessage(EncryptKey)


DESCRIPTOR._options = None

_IGATESERVICE = _descriptor.ServiceDescriptor(
  name='IGateService',
  full_name='proto.IGateService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=219,
  serialized_end=435,
  methods=[
  _descriptor.MethodDescriptor(
    name='sesionSeedRequest',
    full_name='proto.IGateService.sesionSeedRequest',
    index=0,
    containing_service=None,
    input_type=proto_dot_common__pb2._NONE,
    output_type=proto_dot_common__pb2._NONE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='encryptKeyRequest',
    full_name='proto.IGateService.encryptKeyRequest',
    index=1,
    containing_service=None,
    input_type=_ENCRYPTKEYSTR,
    output_type=proto_dot_common__pb2._NONE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='loginRequest',
    full_name='proto.IGateService.loginRequest',
    index=2,
    containing_service=None,
    input_type=proto_dot_common__pb2._LOGINREQUEST,
    output_type=proto_dot_common__pb2._NONE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='callEntityRpc',
    full_name='proto.IGateService.callEntityRpc',
    index=3,
    containing_service=None,
    input_type=proto_dot_common__pb2._RPCMESSAGE,
    output_type=proto_dot_common__pb2._NONE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_IGATESERVICE)

DESCRIPTOR.services_by_name['IGateService'] = _IGATESERVICE


_ICLIENTSERVICE = _descriptor.ServiceDescriptor(
  name='IClientService',
  full_name='proto.IClientService',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=438,
  serialized_end=640,
  methods=[
  _descriptor.MethodDescriptor(
    name='sessionSeedReply',
    full_name='proto.IClientService.sessionSeedReply',
    index=0,
    containing_service=None,
    input_type=proto_dot_common__pb2._NONE,
    output_type=proto_dot_common__pb2._NONE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='encryptKeyReply',
    full_name='proto.IClientService.encryptKeyReply',
    index=1,
    containing_service=None,
    input_type=proto_dot_common__pb2._NONE,
    output_type=proto_dot_common__pb2._NONE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='loginReply',
    full_name='proto.IClientService.loginReply',
    index=2,
    containing_service=None,
    input_type=proto_dot_common__pb2._LOGINREPLY,
    output_type=proto_dot_common__pb2._NONE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='callEntityRpc',
    full_name='proto.IClientService.callEntityRpc',
    index=3,
    containing_service=None,
    input_type=proto_dot_common__pb2._RPCMESSAGE,
    output_type=proto_dot_common__pb2._NONE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ICLIENTSERVICE)

DESCRIPTOR.services_by_name['IClientService'] = _ICLIENTSERVICE

IGateService = service_reflection.GeneratedServiceType('IGateService', (_service.Service,), dict(
  DESCRIPTOR = _IGATESERVICE,
  __module__ = 'proto.client_gate_pb2'
  ))

IGateService_Stub = service_reflection.GeneratedServiceStubType('IGateService_Stub', (IGateService,), dict(
  DESCRIPTOR = _IGATESERVICE,
  __module__ = 'proto.client_gate_pb2'
  ))


IClientService = service_reflection.GeneratedServiceType('IClientService', (_service.Service,), dict(
  DESCRIPTOR = _ICLIENTSERVICE,
  __module__ = 'proto.client_gate_pb2'
  ))

IClientService_Stub = service_reflection.GeneratedServiceStubType('IClientService_Stub', (IClientService,), dict(
  DESCRIPTOR = _ICLIENTSERVICE,
  __module__ = 'proto.client_gate_pb2'
  ))


# @@protoc_insertion_point(module_scope)
