# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/common.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/common.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12proto/common.proto\x12\x05proto\"\x06\n\x04None\"?\n\nDeviceInfo\x12\x0c\n\x04\x61\x64\x64r\x18\x01 \x01(\t\x12\x10\n\x08\x64\x65viceid\x18\x02 \x01(\x0c\x12\x11\n\tsessionid\x18\x03 \x01(\r\"J\n\x0cLoginRequest\x12&\n\x0b\x64\x65vice_info\x18\x01 \x01(\x0b\x32\x11.proto.DeviceInfo\x12\x12\n\nlogin_type\x18\x02 \x01(\r\"Z\n\nLoginReply\x12&\n\x0b\x64\x65vice_info\x18\x01 \x01(\x0b\x32\x11.proto.DeviceInfo\x12\x0f\n\x07retcode\x18\x02 \x01(\r\x12\x13\n\x0bplayer_data\x18\x03 \x01(\x0c\"`\n\nRpcMessage\x12&\n\x0b\x64\x65vice_info\x18\x01 \x01(\x0b\x32\x11.proto.DeviceInfo\x12\x0e\n\x06method\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\r\x12\x0e\n\x06params\x18\x04 \x01(\x0c\x62\x06proto3')
)




_NONE = _descriptor.Descriptor(
  name='None',
  full_name='proto.None',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=35,
)


_DEVICEINFO = _descriptor.Descriptor(
  name='DeviceInfo',
  full_name='proto.DeviceInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='addr', full_name='proto.DeviceInfo.addr', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deviceid', full_name='proto.DeviceInfo.deviceid', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sessionid', full_name='proto.DeviceInfo.sessionid', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=100,
)


_LOGINREQUEST = _descriptor.Descriptor(
  name='LoginRequest',
  full_name='proto.LoginRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_info', full_name='proto.LoginRequest.device_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='login_type', full_name='proto.LoginRequest.login_type', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=176,
)


_LOGINREPLY = _descriptor.Descriptor(
  name='LoginReply',
  full_name='proto.LoginReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_info', full_name='proto.LoginReply.device_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='retcode', full_name='proto.LoginReply.retcode', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='player_data', full_name='proto.LoginReply.player_data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=268,
)


_RPCMESSAGE = _descriptor.Descriptor(
  name='RpcMessage',
  full_name='proto.RpcMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_info', full_name='proto.RpcMessage.device_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='method', full_name='proto.RpcMessage.method', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='proto.RpcMessage.id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='params', full_name='proto.RpcMessage.params', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=270,
  serialized_end=366,
)

_LOGINREQUEST.fields_by_name['device_info'].message_type = _DEVICEINFO
_LOGINREPLY.fields_by_name['device_info'].message_type = _DEVICEINFO
_RPCMESSAGE.fields_by_name['device_info'].message_type = _DEVICEINFO
DESCRIPTOR.message_types_by_name['None'] = _NONE
DESCRIPTOR.message_types_by_name['DeviceInfo'] = _DEVICEINFO
DESCRIPTOR.message_types_by_name['LoginRequest'] = _LOGINREQUEST
DESCRIPTOR.message_types_by_name['LoginReply'] = _LOGINREPLY
DESCRIPTOR.message_types_by_name['RpcMessage'] = _RPCMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

None = _reflection.GeneratedProtocolMessageType('None', (_message.Message,), dict(
  DESCRIPTOR = _NONE,
  __module__ = 'proto.common_pb2'
  # @@protoc_insertion_point(class_scope:proto.None)
  ))
_sym_db.RegisterMessage(None)

DeviceInfo = _reflection.GeneratedProtocolMessageType('DeviceInfo', (_message.Message,), dict(
  DESCRIPTOR = _DEVICEINFO,
  __module__ = 'proto.common_pb2'
  # @@protoc_insertion_point(class_scope:proto.DeviceInfo)
  ))
_sym_db.RegisterMessage(DeviceInfo)

LoginRequest = _reflection.GeneratedProtocolMessageType('LoginRequest', (_message.Message,), dict(
  DESCRIPTOR = _LOGINREQUEST,
  __module__ = 'proto.common_pb2'
  # @@protoc_insertion_point(class_scope:proto.LoginRequest)
  ))
_sym_db.RegisterMessage(LoginRequest)

LoginReply = _reflection.GeneratedProtocolMessageType('LoginReply', (_message.Message,), dict(
  DESCRIPTOR = _LOGINREPLY,
  __module__ = 'proto.common_pb2'
  # @@protoc_insertion_point(class_scope:proto.LoginReply)
  ))
_sym_db.RegisterMessage(LoginReply)

RpcMessage = _reflection.GeneratedProtocolMessageType('RpcMessage', (_message.Message,), dict(
  DESCRIPTOR = _RPCMESSAGE,
  __module__ = 'proto.common_pb2'
  # @@protoc_insertion_point(class_scope:proto.RpcMessage)
  ))
_sym_db.RegisterMessage(RpcMessage)


# @@protoc_insertion_point(module_scope)
