# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/gate_game.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import common_pb2 as proto_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/gate_game.proto',
  package='proto',
  syntax='proto3',
  serialized_options=_b('\200\001\001\220\001\001'),
  serialized_pb=_b('\n\x15proto/gate_game.proto\x12\x05proto\x1a\x12proto/common.proto2q\n\x0cIGameService\x12\x30\n\x0cloginRequest\x12\x13.proto.LoginRequest\x1a\x0b.proto.None\x12/\n\rcallEntityRpc\x12\x11.proto.RpcMessage\x1a\x0b.proto.None2s\n\x12IGameClientService\x12,\n\nloginReply\x12\x11.proto.LoginReply\x1a\x0b.proto.None\x12/\n\rcallEntityRpc\x12\x11.proto.RpcMessage\x1a\x0b.proto.NoneB\x06\x80\x01\x01\x90\x01\x01\x62\x06proto3')
  ,
  dependencies=[proto_dot_common__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_IGAMESERVICE = _descriptor.ServiceDescriptor(
  name='IGameService',
  full_name='proto.IGameService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=52,
  serialized_end=165,
  methods=[
  _descriptor.MethodDescriptor(
    name='loginRequest',
    full_name='proto.IGameService.loginRequest',
    index=0,
    containing_service=None,
    input_type=proto_dot_common__pb2._LOGINREQUEST,
    output_type=proto_dot_common__pb2._NONE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='callEntityRpc',
    full_name='proto.IGameService.callEntityRpc',
    index=1,
    containing_service=None,
    input_type=proto_dot_common__pb2._RPCMESSAGE,
    output_type=proto_dot_common__pb2._NONE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_IGAMESERVICE)

DESCRIPTOR.services_by_name['IGameService'] = _IGAMESERVICE


_IGAMECLIENTSERVICE = _descriptor.ServiceDescriptor(
  name='IGameClientService',
  full_name='proto.IGameClientService',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=167,
  serialized_end=282,
  methods=[
  _descriptor.MethodDescriptor(
    name='loginReply',
    full_name='proto.IGameClientService.loginReply',
    index=0,
    containing_service=None,
    input_type=proto_dot_common__pb2._LOGINREPLY,
    output_type=proto_dot_common__pb2._NONE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='callEntityRpc',
    full_name='proto.IGameClientService.callEntityRpc',
    index=1,
    containing_service=None,
    input_type=proto_dot_common__pb2._RPCMESSAGE,
    output_type=proto_dot_common__pb2._NONE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_IGAMECLIENTSERVICE)

DESCRIPTOR.services_by_name['IGameClientService'] = _IGAMECLIENTSERVICE

IGameService = service_reflection.GeneratedServiceType('IGameService', (_service.Service,), dict(
  DESCRIPTOR = _IGAMESERVICE,
  __module__ = 'proto.gate_game_pb2'
  ))

IGameService_Stub = service_reflection.GeneratedServiceStubType('IGameService_Stub', (IGameService,), dict(
  DESCRIPTOR = _IGAMESERVICE,
  __module__ = 'proto.gate_game_pb2'
  ))


IGameClientService = service_reflection.GeneratedServiceType('IGameClientService', (_service.Service,), dict(
  DESCRIPTOR = _IGAMECLIENTSERVICE,
  __module__ = 'proto.gate_game_pb2'
  ))

IGameClientService_Stub = service_reflection.GeneratedServiceStubType('IGameClientService_Stub', (IGameClientService,), dict(
  DESCRIPTOR = _IGAMECLIENTSERVICE,
  __module__ = 'proto.gate_game_pb2'
  ))


# @@protoc_insertion_point(module_scope)
